("CNR-3 音乐之声" "http://ngcdn003.cnr.cn/live/yyzs/index.m3u8")
("CNR-4 经典音乐广播" "http://ngcdn004.cnr.cn/live/dszs/index.m3u8")
("武汉音乐广播·动感93.6" "http://ls.qingting.fm/live/5011.m3u8")
("上海经典音乐广播" "http://l3.smgtech.net/AppName/1197.m3u8")
("武汉经典音乐广播·岁月悠长，听见好时光" "http://ls.qingting.fm/live/1297.m3u8")
("亳州交通音乐广播" "http://zbbf2.ahbztv.com/live/41c.m3u8")
("新泰音乐广播" "http://live.xtgdw.cn:1935/live/xtlh/playlist.m3u8")
("经典105·山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("山东音乐广播" "http://audiolive302.iqilu.com/sdradioYinyue/sdradio07/playlist.m3u8")
("烟台音乐广播" "http://live.xmcdn.com/live/2716/64.m3u8")
("襄阳交通音乐广播" "http://ls.qingting.fm/live/1308.m3u8")
("哈尔滨古典音乐广播" "https://stream.hrbtv.net/gdpl/playlist.m3u8")
("哈尔滨音乐广播" "https://stream.hrbtv.net/yypl/playlist.m3u8")
("青海交通音乐广播" "http://stream2.qhbtv.com/jtyy/playlist.m3u8")
("杭州音乐时尚广播" "https://live.xmcdn.com/live/1845/64.m3u8")
("吉林音乐广播" "http://stream10.jlntv.cn/fm927/playlist.m3u8")
("Big B Radio亚洲音乐台" "https://antares.dribbcast.com/proxy/apop?mp=/s")
("荆门交通音乐广播" "http://stream.jmtv.com.cn/aac_jtyypl/playlist.m3u8")
("福州音乐广播" "http://live.zohi.tv/audio/s10001-FM893/index.m3u8")
("重庆音乐广播" "http://ls.qingting.fm/live/647.m3u8")
("河南音乐广播" "https://stream.hndt.com/live/yinyue/playlist.m3u8")
("古风音乐" "https://stream.zeno.fm/yq25ha2g268uv")
("雨声轻音乐" "https://stream.zeno.fm/689zc32y4x8uv")
("山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("Raggakings雷鬼音乐频道" "https://raggakings.radio:8443/stream.ogg")
("格莱美音乐台" "http://play-radio-stream3.hndt.com/now/yorSd1X2/chunklist.m3u8")
("云南音乐广播" "http://gbw.ynradio.com/radio/yygb.stream/playlist.m3u8")
("山西音乐广播" "http://radiolive.sxrtv.com/live/yinyue.m3u8")
("滨海音乐广播" "http://traffic.jbh.tjbh.com/live/FM100.5/playlist.m3u8")
("Cinemix电影音乐频道" "http://94.23.51.96:8001/")
("江苏经典流行音乐广播" "http://lzlive.vojs.cn/2wtSfrS/92/live.m3u8?")
("江苏音乐广播" "http://lzlive.vojs.cn/jAmO6Ng/92/live.m3u8?")
("宜昌音乐生活广播" "http://play.3xgd.com/fm/qct.m3u8")
("西安音乐广播" "http://stream3.xiancity.cn/4/sd/live.m3u8")
("上海经典音乐广播" "http://l3.smgtech.net/AppName/947.m3u8")
("上海流行音乐广播" "http://l3.smgtech.net/AppName/1017.m3u8")
("青岛音乐·体育广播" "http://video10.qtv.com.cn/zhiboytgb/manifest.m3u8")
("浙江音乐调频" "http://ali-m-l.cztv.com/channels/lantian/fm968/128k.m3u8")
("石家庄音乐广播" "http://pluslive2.sjzntv.cn/aac_yygb/playlist.m3u8")
("武汉音乐广播" "http://stream.appwuhan.com/yypdzb/sd/live.m3u8")
("郫都综合广播亚洲音乐965" "http://asiafm.vip:8000/fm965")
("AsiaFM亚洲音乐台" "http://asiafm.hk:8000/asiafm")
("AsiaFM高清音乐台" "http://asiafm.hk:8000/asiahd")
("宁波音乐广播" "http://ihzlh.linker.cc/ihzlh/zjnb_ts02_986.m3u8")
("河北汽车音乐台" "https://radio.pull.hebtv.com/live/hebqcyy.m3u8")
("河北音乐广播" "https://radio.pull.hebtv.com/live/hebyy.m3u8")
("CCTV-15音乐伴音" "https://piccpndali.v.myalicdn.com/audio/cctv15_2.m3u8")
("哈尔滨音乐广播" "https://stream.hrbtv.net/yypl/playlist.m3u8")
("湖南音乐之声" "http://a.live.hnradio.com/yypd/radio120k_yypd.m3u8?auth_key=1588751172-0-0-d97b858279c1c86650172b9913ea4af2")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
("海口音乐广播" "https://ls.qingting.fm/live/20010/64k.m3u8")
("音乐之声" "http://ngcdn003.cnr.cn/live/yyzs/index.m3u8")
("CNR-3 音乐之声" "http://antiserver.kuwo.cn/anti.s?rid=MUSIC_190038250&response=res&format=mp3|aac&type=convert_url&br=128kmp3&agent=iPhone&callback=getlink&jpcallback=getlink.mp3")
("邯郸音乐广播" "http://live.hd.hdbs.cn/audio/s10001-2020jjwy/index.m3u8")
("邯郸音乐广播" "http://ls.qingting.fm/live/4601.m3u8")
("昆明交通音乐广播" "http://ls.qingting.fm/live/1936.m3u8")
("怀旧音乐广播" "https://live.ximalaya.com/radio-first-page-app/live/2629/64.m3u8")
("我的音乐分享" "https://stream.zeno.fm/fgbm7mgdjucvv")
("中式婚礼后音乐" "https://stream.zeno.fm/pd3m209fnxhvv")
("古风现代音乐" "https://stream.zeno.fm/tpyqvdsyexhvv")
("西式婚礼音乐" "https://stream.zeno.fm/4vvv2kt70xhvv")
("北京古典音乐广播" "https://stream.zeno.fm/qa9punk6ynhvv")
("105.1成都简单音乐广播" "https://stream.zeno.fm/7brqs9rsbc9uv")
("南京音乐广播" "http://live.xmcdn.com/live/71/64.m3u8")
("威海音乐广播" "http://l1.weihai.tv:8081/hls/kV2209AB37.m3u8")
("烟台音乐广播" "http://live.yantaitv.cn/live/899686f2687848cdbe62b1c27f3b3fc1/111dcc2035384c579cb79a260591a4ea.m3u8")
("菏泽音乐广播" "http://live.hznet.tv:1935/live/live918/32k/tzwj_video.m3u8")
("北海交通音乐广播" "https://rtmp.gdlive.gdmain.com/live/53jo44kl.m3u8")
("南京音乐广播" "http://hls.njgb.com/live_hls/4/playlist.m3u8")
("舟山经济广播（交通音乐）" "https://live1.plus.wifizs.cn/aac_fm97/sd/live.m3u8")
("营口音乐之声" "http://live.xmcdn.com/live/2863/64.m3u8")
("Music of China 中国音乐" "https://vip.wongsong.cn/proxy/wongsong/stream-mp3-WongSong")
("Music of China 中国音乐" "https://vip.wongsong.cn/proxy/wongsong/stream-mp3-WongSong")
("AsiaFM 亚洲音乐台【2023.10.18】" "http://asiafm.hk:8000/asiafm")
("AsiaFM HD音乐台【2023.10.18】" "http://asiafm.hk:8000/asiahd")
("宝鸡音乐频道" "http://vc.bbra.cn:8088/hls/IH88SxBbwG1.m3u8")
("BIG BIG MIX 音乐广播电台" "https://play.gojoy.org/audio/stream")
("枣庄音乐人文广播" "http://stream.zztvzd.com/fm4/sd/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/fm931/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/playlist.m3u8")
("眉山交通音乐广播" "https://live2.scmstv.cn/aac_931/sd/live.m3u8")
("攀枝花交通音乐广播" "http://zb.pzhgd.com:9095/live/dngb.m3u8")
("青岛摩登音乐广播电台" "http://live.xmcdn.com/live/1853/64.m3u8")
("CNR-3 音乐之声" "http://ngcdn003.cnr.cn/live/yyzs/index.m3u8")
("CNR-4 经典音乐广播" "http://ngcdn004.cnr.cn/live/dszs/index.m3u8")
("武汉音乐广播·动感93.6" "http://ls.qingting.fm/live/5011.m3u8")
("上海经典音乐广播" "http://l3.smgtech.net/AppName/1197.m3u8")
("武汉经典音乐广播·岁月悠长，听见好时光" "http://ls.qingting.fm/live/1297.m3u8")
("亳州交通音乐广播" "http://zbbf2.ahbztv.com/live/41c.m3u8")
("新泰音乐广播" "http://live.xtgdw.cn:1935/live/xtlh/playlist.m3u8")
("经典105·山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("山东音乐广播" "http://audiolive302.iqilu.com/sdradioYinyue/sdradio07/playlist.m3u8")
("烟台音乐广播" "http://live.xmcdn.com/live/2716/64.m3u8")
("襄阳交通音乐广播" "http://ls.qingting.fm/live/1308.m3u8")
("哈尔滨古典音乐广播" "https://stream.hrbtv.net/gdpl/playlist.m3u8")
("哈尔滨音乐广播" "https://stream.hrbtv.net/yypl/playlist.m3u8")
("青海交通音乐广播" "http://stream2.qhbtv.com/jtyy/playlist.m3u8")
("杭州音乐时尚广播" "https://live.xmcdn.com/live/1845/64.m3u8")
("吉林音乐广播" "http://stream10.jlntv.cn/fm927/playlist.m3u8")
("Big B Radio亚洲音乐台" "https://antares.dribbcast.com/proxy/apop?mp=/s")
("荆门交通音乐广播" "http://stream.jmtv.com.cn/aac_jtyypl/playlist.m3u8")
("福州音乐广播" "http://live.zohi.tv/audio/s10001-FM893/index.m3u8")
("重庆音乐广播" "http://ls.qingting.fm/live/647.m3u8")
("河南音乐广播" "https://stream.hndt.com/live/yinyue/playlist.m3u8")
("古风音乐" "https://stream.zeno.fm/yq25ha2g268uv")
("雨声轻音乐" "https://stream.zeno.fm/689zc32y4x8uv")
("山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("Raggakings雷鬼音乐频道" "https://raggakings.radio:8443/stream.ogg")
("格莱美音乐台" "http://play-radio-stream3.hndt.com/now/yorSd1X2/chunklist.m3u8")
("云南音乐广播" "http://gbw.ynradio.com/radio/yygb.stream/playlist.m3u8")
("山西音乐广播" "http://radiolive.sxrtv.com/live/yinyue.m3u8")
("滨海音乐广播" "http://traffic.jbh.tjbh.com/live/FM100.5/playlist.m3u8")
("Cinemix电影音乐频道" "http://94.23.51.96:8001/")
("江苏经典流行音乐广播" "http://lzlive.vojs.cn/2wtSfrS/92/live.m3u8?")
("江苏音乐广播" "http://lzlive.vojs.cn/jAmO6Ng/92/live.m3u8?")
("宜昌音乐生活广播" "http://play.3xgd.com/fm/qct.m3u8")
("西安音乐广播" "http://stream3.xiancity.cn/4/sd/live.m3u8")
("上海经典音乐广播" "http://l3.smgtech.net/AppName/947.m3u8")
("上海流行音乐广播" "http://l3.smgtech.net/AppName/1017.m3u8")
("青岛音乐·体育广播" "http://video10.qtv.com.cn/zhiboytgb/manifest.m3u8")
("浙江音乐调频" "http://ali-m-l.cztv.com/channels/lantian/fm968/128k.m3u8")
("石家庄音乐广播" "http://pluslive2.sjzntv.cn/aac_yygb/playlist.m3u8")
("武汉音乐广播" "http://stream.appwuhan.com/yypdzb/sd/live.m3u8")
("郫都综合广播亚洲音乐965" "http://asiafm.vip:8000/fm965")
("AsiaFM亚洲音乐台" "http://asiafm.hk:8000/asiafm")
("AsiaFM高清音乐台" "http://asiafm.hk:8000/asiahd")
("宁波音乐广播" "http://ihzlh.linker.cc/ihzlh/zjnb_ts02_986.m3u8")
("河北汽车音乐台" "https://radio.pull.hebtv.com/live/hebqcyy.m3u8")
("河北音乐广播" "https://radio.pull.hebtv.com/live/hebyy.m3u8")
("CCTV-15音乐伴音" "https://piccpndali.v.myalicdn.com/audio/cctv15_2.m3u8")
("哈尔滨音乐广播" "https://stream.hrbtv.net/yypl/playlist.m3u8")
("湖南音乐之声" "http://a.live.hnradio.com/yypd/radio120k_yypd.m3u8?auth_key=1588751172-0-0-d97b858279c1c86650172b9913ea4af2")
("海口音乐广播" "https://ls.qingting.fm/live/20010/64k.m3u8")
("音乐之声" "http://ngcdn003.cnr.cn/live/yyzs/index.m3u8")
("CNR-3 音乐之声" "http://antiserver.kuwo.cn/anti.s?rid=MUSIC_190038250&response=res&format=mp3|aac&type=convert_url&br=128kmp3&agent=iPhone&callback=getlink&jpcallback=getlink.mp3")
("邯郸音乐广播" "http://live.hd.hdbs.cn/audio/s10001-2020jjwy/index.m3u8")
("邯郸音乐广播" "http://ls.qingting.fm/live/4601.m3u8")
("昆明交通音乐广播" "http://ls.qingting.fm/live/1936.m3u8")
("怀旧音乐广播" "https://live.ximalaya.com/radio-first-page-app/live/2629/64.m3u8")
("我的音乐分享" "https://stream.zeno.fm/fgbm7mgdjucvv")
("中式婚礼后音乐" "https://stream.zeno.fm/pd3m209fnxhvv")
("古风现代音乐" "https://stream.zeno.fm/tpyqvdsyexhvv")
("西式婚礼音乐" "https://stream.zeno.fm/4vvv2kt70xhvv")
("北京古典音乐广播" "https://stream.zeno.fm/qa9punk6ynhvv")
("105.1成都简单音乐广播" "https://stream.zeno.fm/7brqs9rsbc9uv")
("南京音乐广播" "http://live.xmcdn.com/live/71/64.m3u8")
("威海音乐广播" "http://l1.weihai.tv:8081/hls/kV2209AB37.m3u8")
("烟台音乐广播" "http://live.yantaitv.cn/live/899686f2687848cdbe62b1c27f3b3fc1/111dcc2035384c579cb79a260591a4ea.m3u8")
("菏泽音乐广播" "http://live.hznet.tv:1935/live/live918/32k/tzwj_video.m3u8")
("北海交通音乐广播" "https://rtmp.gdlive.gdmain.com/live/53jo44kl.m3u8")
("南京音乐广播" "http://hls.njgb.com/live_hls/4/playlist.m3u8")
("舟山经济广播（交通音乐）" "https://live1.plus.wifizs.cn/aac_fm97/sd/live.m3u8")
("营口音乐之声" "http://live.xmcdn.com/live/2863/64.m3u8")
("Music of China 中国音乐" "https://vip.wongsong.cn/proxy/wongsong/stream-mp3-WongSong")
("Music of China 中国音乐" "https://vip.wongsong.cn/proxy/wongsong/stream-mp3-WongSong")
("AsiaFM 亚洲音乐台【2023.10.18】" "http://asiafm.hk:8000/asiafm")
("AsiaFM HD音乐台【2023.10.18】" "http://asiafm.hk:8000/asiahd")
("AsiaFM 亚洲音乐台【2023.10.18】" "http://asiafm.hk:8000/asiafm")
("AsiaFM HD音乐台【2023.10.18】" "http://asiafm.hk:8000/asiahd")
("菏泽音乐广播" "http://live.hznet.tv:1935/live/live918/32k/tzwj_video.m3u8")
("古风现代音乐" "https://stream.zeno.fm/tpyqvdsyexhvv")
("中式婚礼后音乐" "https://stream.zeno.fm/pd3m209fnxhvv")
("经典105·山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("Music of China 中国音乐" "https://vip.wongsong.cn/proxy/wongsong/stream-mp3-WongSong")
("青岛音乐·体育广播" "http://video10.qtv.com.cn/zhiboytgb/manifest.m3u8")
("襄阳交通音乐广播" "http://ls.qingting.fm/live/1308.m3u8")
("山东经典音乐广播" "http://audiolive302.iqilu.com/sdradioShenghuo/sdradio04/playlist.m3u8")
("怀旧音乐广播" "https://live.ximalaya.com/radio-first-page-app/live/2629/64.m3u8")
("宜昌音乐生活广播" "http://play.3xgd.com/fm/qct.m3u8")
("江苏音乐广播" "http://lzlive.vojs.cn/jAmO6Ng/92/live.m3u8?")
("Big B Radio亚洲音乐台" "https://antares.dribbcast.com/proxy/apop?mp=/s")
("吉林音乐广播" "http://stream10.jlntv.cn/fm927/playlist.m3u8")
("浙江音乐调频" "http://ali-m-l.cztv.com/channels/lantian/fm968/128k.m3u8")
("山东音乐广播" "http://audiolive302.iqilu.com/sdradioYinyue/sdradio07/playlist.m3u8")
("浙江音乐调频" "http://ali-m-l.cztv.com/channels/lantian/fm968/128k.m3u8")
("宝鸡音乐频道" "http://vc.bbra.cn:8088/hls/IH88SxBbwG1.m3u8")
("宝鸡音乐频道" "http://vc.bbra.cn:8088/hls/IH88SxBbwG1.m3u8")
("宝鸡音乐频道" "http://vc.bbra.cn:8088/hls/IH88SxBbwG1.m3u8")
("浙江音乐调频" "http://ali-m-l.cztv.com/channels/lantian/fm968/128k.m3u8")
("我的音乐分享" "https://stream.zeno.fm/fgbm7mgdjucvv")
("我的音乐分享" "https://stream.zeno.fm/fgbm7mgdjucvv")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
("BIG BIG MIX 音乐广播电台" "https://play.gojoy.org/audio/stream")
("BIG BIG MIX 音乐广播电台" "https://play.gojoy.org/audio/stream")
("BIG BIG MIX 音乐广播电台" "https://play.gojoy.org/audio/stream")
("枣庄音乐人文广播" "http://stream.zztvzd.com/fm4/sd/live.m3u8")
("枣庄音乐人文广播" "http://stream.zztvzd.com/fm4/sd/live.m3u8")
("枣庄音乐人文广播" "http://stream.zztvzd.com/fm4/sd/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/fm931/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/fm931/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/fm931/live.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/playlist.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/playlist.m3u8")
("阳泉经济广播最爱音乐台" "https://live.yqrtv.com/aac_musicyq/playlist.m3u8")
("眉山交通音乐广播" "https://live2.scmstv.cn/aac_931/sd/live.m3u8")
("眉山交通音乐广播" "https://live2.scmstv.cn/aac_931/sd/live.m3u8")
("眉山交通音乐广播" "https://live2.scmstv.cn/aac_931/sd/live.m3u8")
("攀枝花交通音乐广播" "http://zb.pzhgd.com:9095/live/dngb.m3u8")
("攀枝花交通音乐广播" "http://zb.pzhgd.com:9095/live/dngb.m3u8")
("攀枝花交通音乐广播" "http://zb.pzhgd.com:9095/live/dngb.m3u8")
("青岛摩登音乐广播电台" "http://live.xmcdn.com/live/1853/64.m3u8")
("青岛摩登音乐广播电台" "http://live.xmcdn.com/live/1853/64.m3u8")
("青岛摩登音乐广播电台" "http://live.xmcdn.com/live/1853/64.m3u8")
("CMC加州音乐" "https://cmc-ono.amagi.tv/playlist720_p.m3u8")
